export enum APP_URL_LIST {
  HOME_URL = "/",
  LOAN = "/loans",
  KARMA = "/Karma",
  NOT_FOUND_URL = "*",
  REPORT = "./report",
  USER_URL = "/user",
  SAVINGS = "/savings",
  SIGNIN_URL = "/signin",
  SERVICES = "./Services",
  WHITELIST = "/Whitelist",
  AUDIT_LOGS = "./auditLogs",
  GUARANTORS = "/guarantors",
  PREFERENCES = "./Preferences",
  SETTLEMENTS = "./settlements",
  FEES_CHARGES = "/fees-Charges",
  DASH_BOARD_URL = "/dashboard",
  ORGANIZATION = "./organization",
  LOAN_PRODUCTS = "./loan-products",
  TRANSACTIONS = "./transactions",
  LOAN_REQUESTS = "/loan-requests",
  DECISION_MODELS = "/decision-models",
  USERDETAILS_URL = "/user-details",
  SERVICE_ACCOUNT = "./savince-Account",
  SAVINGS_PRODUCT = "/savings-Product",
}
